name: steady_solutions
description: "Steady Solutions Mobile application."


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  get: ^4.6.5
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  flutter_otp_text_field: ^1.1.0+2
  flutter_svg: ^2.0.5
  encrypt: null
  http: null
  #jiffy: 6.0.0
  swipeable_page_route: ^0.4.3
  package_info_plus: any
  percent_indicator: ^4.0.1
  chewie: ^1.7.1
  video_player: ^2.7.1
  native_device_orientation: ^2.0.3
  firebase_messaging: ^15.0.1
  flutter_local_notifications: ^17.1.2
  flutter_staggered_grid_view: ^0.7.0
  audioplayers: ^6.0.0
  shimmer: ^3.0.0
  get_storage: ^2.1.1
  intl: any
  syncfusion_flutter_datagrid: ^26.1.35
  getwidget: ^4.0.0
  #syncfusion_flutter_charts: ^23.1.42
  flutter_charts: 0.5.2
  syncfusion_flutter_gauges: ^26.1.35
  syncfusion_flutter_charts: ^26.1.35
  persistent_bottom_nav_bar: ^5.0.2
  loading_animation_widget: ^1.2.0+4
  simple_animations: ^5.0.2
  flutter_keyboard_visibility: ^6.0.0
  page_transition: 2.1.0
  local_auth: ^2.1.8
  device_info_plus: ^10.1.0
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  fl_chart: ^0.68.0
  syncfusion_flutter_calendar: ^26.1.35
  rive: ^0.13.1
  provider: ^6.1.2
  flutter_localization: ^0.2.0
  ionicons: ^0.2.2
  file_picker: ^8.0.0+1
  material_dialogs: ^1.1.4
  qr_code_scanner: ^1.0.1
  toggle_switch: ^2.3.0
  font_awesome_flutter: ^10.7.0
  lottie: ^2.7.0
  flutter_speed_dial: ^7.0.0
  simple_animated_icon: ^1.1.0
  url_launcher: ^6.2.6
  loader_overlay: ^4.0.0
  geolocator: ^12.0.0
  flutter_spinkit: ^5.2.1
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_inappwebview: ^6.0.0
  syncfusion_flutter_treemap: ^26.1.35
  #syncfusion_flutter_pdfviewer: ^26.1.35
  syncfusion_flutter_pdf: ^26.1.35
  syncfusion_flutter_datagrid_export: ^26.1.35
  syncfusion_flutter_xlsio: ^26.1.35
  card_swiper: ^3.0.1
  glossy: ^0.0.4
  flutter_localizations:
    sdk: flutter
  share_plus: ^9.0.0
  screenshot: ^3.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter






############## ICON SETTINGS 


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/oms_white.png" 

  adaptive_icon_background:  "#1977DD" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icons/oms_white.png" # only available for Android 8.0 devices and above
  #adaptive_icon_monochrome: "assets/icons/oms_white.png" # only available for Android 13 devices and above 
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#1977DD"
  background_color: "#1977DD"
  web:
    generate: true
    image_path: "assets/icons/oms_white.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/oms_white.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/oms_white.png"



############ LINTS

  # flutter_lints: ^3.0.2
  # lints: ^3.0.0
  # flutter analyze # Run Dart Analyzer
  # flutter pub run flutter_lints:main # Run Flutter Lints
  # dartfmt -w lib/ # Format all Dart files in the "lib" directory


########################## FONTS AND IMAGES
flutter:
  generate: true

  fonts:
    - family: ProductSans
      fonts:
      - asset: assets/fonts/Product-Sans-Regular.ttf
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/images/logos/
    - assets/json_animations/
    - assets/images/backgrounds/
  uses-material-design: true



