name: steady_solutions
description: "Steady Solutions Mobile application."


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  google_fonts: ^4.0.3
  get: ^4.6.5
  firebase_core: ^2.15.1
  firebase_auth: ^4.4.2
  flutter_otp_text_field: ^1.1.0+2
  flutter_svg: ^2.0.5
  encrypt: null
  http: null
  #jiffy: 6.0.0
  swipeable_page_route: ^0.3.0
  package_info_plus: any
  percent_indicator: ^4.0.1
  chewie: ^1.7.1
  video_player: ^2.7.1
  native_device_orientation: ^1.1.4
  firebase_messaging: ^14.6.7
  flutter_local_notifications: ^15.1.1
  flutter_staggered_grid_view: ^0.7.0
  audioplayers: ^5.1.0
  shimmer: ^3.0.0
  get_storage: ^2.1.1
  intl: any
  syncfusion_flutter_datagrid: ^25.1.42
  getwidget: ^4.0.0
  #syncfusion_flutter_charts: ^23.1.42
  flutter_charts: 0.5.2
  syncfusion_flutter_gauges: ^25.1.42
  syncfusion_flutter_charts: ^25.1.42+1
  persistent_bottom_nav_bar: ^5.0.2
  loading_animation_widget: ^1.2.0+4
  simple_animations: 3.0.0
  flutter_keyboard_visibility: ^6.0.0
  page_transition: 2.1.0
  local_auth: ^2.1.8
  device_info_plus: ^9.1.1
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  fl_chart: ^0.67.0
  syncfusion_flutter_calendar: ^25.2.3
  rive: ^0.13.1
  provider: ^6.1.2
  flutter_localization: ^0.2.0
  ionicons: ^0.2.2
  file_picker: ^8.0.0+1
  material_dialogs: ^1.1.4
  qr_code_scanner: ^1.0.1
  toggle_switch: ^2.3.0
  font_awesome_flutter: ^10.7.0
  lottie: ^2.7.0
  flutter_speed_dial: ^7.0.0
  simple_animated_icon: ^1.1.0
  url_launcher: ^6.2.6
  loader_overlay: ^4.0.0
  geolocator: ^12.0.0
  flutter_spinkit: ^5.2.1
  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  lints: ^3.0.0
  # flutter analyze # Run Dart Analyzer
  # flutter pub run flutter_lints:main # Run Flutter Lints
  # dartfmt -w lib/ # Format all Dart files in the "lib" directory
flutter:
  generate: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/images/logos/
    - assets/json_animations/
  uses-material-design: true



